export const PATH = {
  ROOT: "/",
  HOME: "/home",
  TODAY_MEAL_SCORE: "/home/date-meal-score",
  ONBOARDING: "/onboarding",
  RECOMMEND: "/recommend",
  COMPARE: "/compare",
  PROFILE: "/profile",
  TERMS: "/terms",
  MEAL_RECORD: "/meal-record",
  MEAL_RECORD_ADD: "/meal-record/add",
  MEAL_RECORD_ADD_SEARCH: "/meal-record/add/search",
  MEAL_RECORD_ADD_SEARCH_DETAIL: "/meal-record/add/search/detail",
  MEAL_CAMERA: "/meal-record/add/camera",
  NUTRITION_ADD: "/nutrition-add",
  NUTRITION_CAMERA: "/nutrition-camera",
  NUTRITION_ADD_DETAIL: "/nutrition-add/detail",
  BRAND_SEARCH: "/brand-search",
  BRAND_MENU_SEARCH: "/brand-search/menu",
  COMPARE_MENU_SEARCH: "/compare/menu-search",
  COMPARE_SELECT_MENU: "/compare/select-menu",
};
